eureka:
  instance:
    hostname: localhost
  client:
      register-with-eureka: false
      fetch-registry: false
      serviceUri:
        defaultZone: http://localhost:8761/eureka
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}


server:
  port: 8761
spring:
  application:
    name: discovery-server

