spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: inventory-service

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka


server:
  port: 0