version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_inventory_db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory-service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
